server:
  port: 8001

mybatis:
  configLocation: classpath:mybatis/mybatis-config.xml
  typeAliasesPackage: com.xiaopay.entity
  mapperLocations: classpath:mybatis/mapper/**/*.xml

spring:
  application:
    name: microservice-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01
    username: root
    password: mysql

eureka:
  client:   #将客户端注册到eureka服务端列表中
    service-url:
      #单机 defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    instance-id: microservice-dept-8001-xxx
    prefer-ip-address: true #访问路径可以显示IP地址
  server:
    enable-self-preservation: false #自我保护机制

info:
  app.name: xiaopay-microservice
  company.name: az.xiaopay
  build.artifactId: $project.artifactId$
  build.version: $project.version$